server:
  port: 8080

spring:
  profiles:
    active: dev
    include: alipay

jwt:
  secret: novel!#20191230
  expiration: 604800

#缓存管理密码
cache:
  manager:
    password: novel@2020117


# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice/*
  # 匹配链接 （多个用逗号分隔）
  urlPatterns: /book/addBookComment,/user/addFeedBack,/author/addBook,/author/addBookContent,/author/register.html



